# Generated by Django 3.2 on 2022-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontionBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(blank=True, max_length=255, null=True, verbose_name='productId')),
                ('productType', models.CharField(blank=True, max_length=255, null=True, verbose_name='productType')),
                ('imageUrl', models.URLField(blank=True, max_length=256, null=True, verbose_name='Image URL')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='currency')),
                ('sku', models.CharField(blank=True, max_length=10, null=True, verbose_name='currency')),
                ('urlSlug', models.CharField(blank=True, max_length=255, null=True, verbose_name='currency')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('formatType', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
            ],
        ),
    ]
